service: hello-world
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  runtime: provided.al2
  architecture: arm64
  deploymentBucket:
    name: ssot-lambda-build-deploy
  
package:
    artifact: ../bin/hello-world.zip

functions:
  hello-world:
    name: hello-world-${self:provider.stage}
    handler: bootstrap
    url: true
