// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ACLMutationResult struct {
	Success bool       `json:"success"`
	Message string     `json:"message"`
	Record  *ACLRecord `json:"record,omitempty"`
}

type ACLRecord struct {
	PrincipalID  string         `json:"principalID"`
	Groups       []string       `json:"groups"`
	Permissions  []*Permission  `json:"permissions"`
	FieldFilters []*FieldFilter `json:"fieldFilters"`
	UpdatedAt    string         `json:"updatedAt"`
}

type AddGroupACLInput struct {
	GroupName    string              `json:"groupName"`
	Permissions  []*PermissionInput  `json:"permissions"`
	FieldFilters []*FieldFilterInput `json:"fieldFilters,omitempty"`
}

type AddUserACLInput struct {
	Email        string              `json:"email"`
	Groups       []string            `json:"groups"`
	Permissions  []*PermissionInput  `json:"permissions"`
	FieldFilters []*FieldFilterInput `json:"fieldFilters,omitempty"`
}

type FieldFilter struct {
	Field       string   `json:"field"`
	IncludeList []string `json:"includeList"`
	ExcludeList []string `json:"excludeList"`
	FilterType  string   `json:"filterType"`
}

type FieldFilterInput struct {
	Field       string   `json:"field"`
	IncludeList []string `json:"includeList"`
	ExcludeList []string `json:"excludeList"`
	FilterType  string   `json:"filterType"`
}

type LoanCashFlow struct {
	LoanCode                         string   `json:"loanCode"`
	MaxHmy                           *string  `json:"maxHmy,omitempty"`
	AccrualEndDate                   *string  `json:"accrualEndDate,omitempty"`
	AccrualStartDate                 *string  `json:"accrualStartDate,omitempty"`
	Balance                          *float64 `json:"balance,omitempty"`
	CapitalizedFee                   *float64 `json:"capitalizedFee,omitempty"`
	CapitalizedInterest              *float64 `json:"capitalizedInterest,omitempty"`
	CapitalizedLoanAdministrationFee *float64 `json:"capitalizedLoanAdministrationFee,omitempty"`
	CapitalizedOtherFees             *float64 `json:"capitalizedOtherFees,omitempty"`
	Commitment                       *float64 `json:"commitment,omitempty"`
	DrawActualPrincipal              *float64 `json:"drawActualPrincipal,omitempty"`
	EBalance                         *float64 `json:"eBalance,omitempty"`
	GlPeriodDate                     *string  `json:"glPeriodDate,omitempty"`
	Interest                         *float64 `json:"interest,omitempty"`
	LeverageActivity                 *float64 `json:"leverageActivity,omitempty"`
	LeverageBalance                  *float64 `json:"leverageBalance,omitempty"`
	LeverageInterest                 *float64 `json:"leverageInterest,omitempty"`
	LoanDesc                         *string  `json:"loanDesc,omitempty"`
	PaymentNumber                    *string  `json:"paymentNumber,omitempty"`
	PostDate                         *string  `json:"postDate,omitempty"`
	PropertyCode                     *string  `json:"propertyCode,omitempty"`
	PropertyName                     *string  `json:"propertyName,omitempty"`
	SBalance                         *float64 `json:"sBalance,omitempty"`
	Status                           *string  `json:"status,omitempty"`
}

type LoanCashFlows struct {
	ByLoanCode []*LoanCashFlow `json:"byLoanCode"`
}

type Mutation struct {
}

type Permission struct {
	Table  string `json:"table"`
	Action string `json:"action"`
}

type PermissionInput struct {
	Table  string `json:"table"`
	Action string `json:"action"`
}

type Query struct {
}

type SsotReportsAdministratorConfiguration struct {
	ListACLRecords []*ACLRecord `json:"listACLRecords"`
}

type UpdateGroupACLInput struct {
	GroupName    string              `json:"groupName"`
	Permissions  []*PermissionInput  `json:"permissions"`
	FieldFilters []*FieldFilterInput `json:"fieldFilters,omitempty"`
}

type UpdateUserACLInput struct {
	Email        string              `json:"email"`
	Groups       []string            `json:"groups,omitempty"`
	Permissions  []*PermissionInput  `json:"permissions,omitempty"`
	FieldFilters []*FieldFilterInput `json:"fieldFilters,omitempty"`
}
