// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoanCashFlow struct {
	LoanCode         string   `json:"loanCode"`
	MaxHmy           *string  `json:"maxHmy,omitempty"`
	Balance          *float64 `json:"balance,omitempty"`
	Commitment       *float64 `json:"commitment,omitempty"`
	Ebalance         *float64 `json:"ebalance,omitempty"`
	GlPerioddate     *string  `json:"glPerioddate,omitempty"`
	Interest         *float64 `json:"interest,omitempty"`
	LeverageActivity *float64 `json:"leverageActivity,omitempty"`
	LeverageBalance  *float64 `json:"leverageBalance,omitempty"`
	LeverageInterest *float64 `json:"leverageInterest,omitempty"`
	Loandesc         *string  `json:"loandesc,omitempty"`
	Periodend        *string  `json:"periodend,omitempty"`
	Postdate         *string  `json:"postdate,omitempty"`
	Propertycode     *string  `json:"propertycode,omitempty"`
	Propertyname     *string  `json:"propertyname,omitempty"`
	Sbalance         *float64 `json:"sbalance,omitempty"`
	Status           *string  `json:"status,omitempty"`
}

type LoanCashFlows struct {
	ByLoanCode []*LoanCashFlow `json:"byLoanCode"`
}

type Query struct {
}
