package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"ssot/gql/graphql/graph/model"
	"ssot/gql/graphql/internal/auth"
)

// ByLoanCode is the resolver for the byLoanCode field.
func (r *loanCashFlowsResolver) ByLoanCode(ctx context.Context, obj *model.LoanCashFlows, loanCode string) ([]*model.LoanCashFlow, error) {
	// Check authentication
	_, err := auth.GetUserFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return r.ServiceManager.LoanCashFlowService.GetByLoanCode(ctx, loanCode)
}

// LoanCashFlow is the resolver for the loanCashFlow field.
func (r *queryResolver) LoanCashFlow(ctx context.Context) (*model.LoanCashFlows, error) {
	// Check authentication
	_, err := auth.GetUserFromContext(ctx)
	if err != nil {
		return nil, err
	}

	return &model.LoanCashFlows{}, nil
}

// LoanCashFlows returns LoanCashFlowsResolver implementation.
func (r *Resolver) LoanCashFlows() LoanCashFlowsResolver { return &loanCashFlowsResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type loanCashFlowsResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
