package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"fmt"
	"ssot/api/graphql/graph/model"
)

// LoanCashFlow is the resolver for the loanCashFlow field.
func (r *queryResolver) LoanCashFlow(ctx context.Context) (*model.LoanCashFlows, error) {
	panic(fmt.Errorf("not implemented: LoanCashFlow - loanCashFlow"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
